<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class frmSetupMenuUtama
    Inherits DevExpress.XtraBars.Ribbon.RibbonForm

    'Form overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        If disposing AndAlso components IsNot Nothing Then
            components.Dispose()
        End If
        MyBase.Dispose(disposing)
    End Sub

    'Required by the Windows Form Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Windows Form Designer
    'It can be modified using the Windows Form Designer.  
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmSetupMenuUtama))
        Me.RibbonControl = New DevExpress.XtraBars.Ribbon.RibbonControl()
        Me.ApplicationMenu1 = New DevExpress.XtraBars.Ribbon.ApplicationMenu(Me.components)
        Me.BarButtonItem1 = New DevExpress.XtraBars.BarButtonItem()
        Me.BarButtonItem2 = New DevExpress.XtraBars.BarButtonItem()
        Me.ImageCollection1 = New DevExpress.Utils.ImageCollection(Me.components)
        Me.BarButtonItem3 = New DevExpress.XtraBars.BarButtonItem()
        Me.BarButtonItem4 = New DevExpress.XtraBars.BarButtonItem()
        Me.BarStaticItem1 = New DevExpress.XtraBars.BarStaticItem()
        Me.BarButtonItem5 = New DevExpress.XtraBars.BarButtonItem()
        Me.BarButtonItem6 = New DevExpress.XtraBars.BarButtonItem()
        Me.BarButtonItem7 = New DevExpress.XtraBars.BarButtonItem()
        Me.BarButtonItem8 = New DevExpress.XtraBars.BarButtonItem()
        Me.BarButtonItem9 = New DevExpress.XtraBars.BarButtonItem()
        Me.BarButtonItem10 = New DevExpress.XtraBars.BarButtonItem()
        Me.BarButtonItem11 = New DevExpress.XtraBars.BarButtonItem()
        Me.BarButtonItem12 = New DevExpress.XtraBars.BarButtonItem()
        Me.RibbonGalleryBarItem1 = New DevExpress.XtraBars.RibbonGalleryBarItem()
        Me.RibbonPage1 = New DevExpress.XtraBars.Ribbon.RibbonPage()
        Me.RibbonPageGroup1 = New DevExpress.XtraBars.Ribbon.RibbonPageGroup()
        Me.RibbonPageGroup2 = New DevExpress.XtraBars.Ribbon.RibbonPageGroup()
        Me.RibbonPageGroup3 = New DevExpress.XtraBars.Ribbon.RibbonPageGroup()
        Me.RibbonPage2 = New DevExpress.XtraBars.Ribbon.RibbonPage()
        Me.RibbonPageGroup4 = New DevExpress.XtraBars.Ribbon.RibbonPageGroup()
        Me.RibbonStatusBar = New DevExpress.XtraBars.Ribbon.RibbonStatusBar()
        Me.DocumentManager1 = New DevExpress.XtraBars.Docking2010.DocumentManager(Me.components)
        Me.TabbedView1 = New DevExpress.XtraBars.Docking2010.Views.Tabbed.TabbedView(Me.components)
        Me.Timer1 = New System.Windows.Forms.Timer(Me.components)
        Me.BarButtonItem13 = New DevExpress.XtraBars.BarButtonItem()
        CType(Me.RibbonControl, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ApplicationMenu1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ImageCollection1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.DocumentManager1, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.TabbedView1, System.ComponentModel.ISupportInitialize).BeginInit()
        Me.SuspendLayout()
        '
        'RibbonControl
        '
        Me.RibbonControl.ApplicationButtonDropDownControl = Me.ApplicationMenu1
        Me.RibbonControl.ExpandCollapseItem.Id = 0
        Me.RibbonControl.Images = Me.ImageCollection1
        Me.RibbonControl.Items.AddRange(New DevExpress.XtraBars.BarItem() {Me.RibbonControl.ExpandCollapseItem, Me.BarButtonItem1, Me.BarButtonItem2, Me.BarButtonItem3, Me.BarButtonItem4, Me.BarStaticItem1, Me.BarButtonItem5, Me.BarButtonItem6, Me.BarButtonItem7, Me.BarButtonItem8, Me.BarButtonItem9, Me.BarButtonItem10, Me.BarButtonItem11, Me.BarButtonItem12, Me.RibbonGalleryBarItem1, Me.BarButtonItem13})
        Me.RibbonControl.LargeImages = Me.ImageCollection1
        Me.RibbonControl.Location = New System.Drawing.Point(0, 0)
        Me.RibbonControl.MaxItemId = 21
        Me.RibbonControl.Name = "RibbonControl"
        Me.RibbonControl.Pages.AddRange(New DevExpress.XtraBars.Ribbon.RibbonPage() {Me.RibbonPage1, Me.RibbonPage2})
        Me.RibbonControl.Size = New System.Drawing.Size(790, 143)
        Me.RibbonControl.StatusBar = Me.RibbonStatusBar
        '
        'ApplicationMenu1
        '
        Me.ApplicationMenu1.ItemLinks.Add(Me.BarButtonItem1)
        Me.ApplicationMenu1.ItemLinks.Add(Me.BarButtonItem2)
        Me.ApplicationMenu1.Name = "ApplicationMenu1"
        Me.ApplicationMenu1.Ribbon = Me.RibbonControl
        '
        'BarButtonItem1
        '
        Me.BarButtonItem1.Caption = "LOG OUT"
        Me.BarButtonItem1.Id = 3
        Me.BarButtonItem1.ImageIndex = 122
        Me.BarButtonItem1.Name = "BarButtonItem1"
        '
        'BarButtonItem2
        '
        Me.BarButtonItem2.Caption = "EXIT"
        Me.BarButtonItem2.Id = 4
        Me.BarButtonItem2.ImageIndex = 115
        Me.BarButtonItem2.Name = "BarButtonItem2"
        '
        'ImageCollection1
        '
        Me.ImageCollection1.ImageSize = New System.Drawing.Size(48, 48)
        Me.ImageCollection1.ImageStream = CType(resources.GetObject("ImageCollection1.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ImageCollection1.Images.SetKeyName(0, "C3M (0).png")
        Me.ImageCollection1.Images.SetKeyName(1, "C3M (1).png")
        Me.ImageCollection1.Images.SetKeyName(2, "C3M (2).png")
        Me.ImageCollection1.Images.SetKeyName(3, "C3M (3).png")
        Me.ImageCollection1.Images.SetKeyName(4, "C3M (4).png")
        Me.ImageCollection1.Images.SetKeyName(5, "C3M (5).png")
        Me.ImageCollection1.Images.SetKeyName(6, "C3M (6).png")
        Me.ImageCollection1.Images.SetKeyName(7, "C3M (7).png")
        Me.ImageCollection1.Images.SetKeyName(8, "C3M (8).png")
        Me.ImageCollection1.Images.SetKeyName(9, "C3M (9).png")
        Me.ImageCollection1.Images.SetKeyName(10, "C3M (10).png")
        Me.ImageCollection1.Images.SetKeyName(11, "C3M (11).png")
        Me.ImageCollection1.Images.SetKeyName(12, "C3M (12).png")
        Me.ImageCollection1.Images.SetKeyName(13, "C3M (13).png")
        Me.ImageCollection1.Images.SetKeyName(14, "C3M (14).png")
        Me.ImageCollection1.Images.SetKeyName(15, "C3M (15).png")
        Me.ImageCollection1.Images.SetKeyName(16, "C3M (16).png")
        Me.ImageCollection1.Images.SetKeyName(17, "C3M (17).png")
        Me.ImageCollection1.Images.SetKeyName(18, "C3M (18).png")
        Me.ImageCollection1.Images.SetKeyName(19, "C3M (19).png")
        Me.ImageCollection1.Images.SetKeyName(20, "C3M (20).png")
        Me.ImageCollection1.Images.SetKeyName(21, "C3M (21).png")
        Me.ImageCollection1.Images.SetKeyName(22, "C3M (22).png")
        Me.ImageCollection1.Images.SetKeyName(23, "C3M (23).png")
        Me.ImageCollection1.Images.SetKeyName(24, "C3M (24).png")
        Me.ImageCollection1.Images.SetKeyName(25, "C3M (25).png")
        Me.ImageCollection1.Images.SetKeyName(26, "C3M (26).png")
        Me.ImageCollection1.Images.SetKeyName(27, "C3M (27).png")
        Me.ImageCollection1.Images.SetKeyName(28, "C3M (28).png")
        Me.ImageCollection1.Images.SetKeyName(29, "C3M (29).png")
        Me.ImageCollection1.Images.SetKeyName(30, "C3M (30).png")
        Me.ImageCollection1.Images.SetKeyName(31, "C3M (31).png")
        Me.ImageCollection1.Images.SetKeyName(32, "C3M (32).png")
        Me.ImageCollection1.Images.SetKeyName(33, "C3M (33).png")
        Me.ImageCollection1.Images.SetKeyName(34, "C3M (34).png")
        Me.ImageCollection1.Images.SetKeyName(35, "C3M (35).png")
        Me.ImageCollection1.Images.SetKeyName(36, "C3M (36).png")
        Me.ImageCollection1.Images.SetKeyName(37, "C3M (37).png")
        Me.ImageCollection1.Images.SetKeyName(38, "C3M (38).png")
        Me.ImageCollection1.Images.SetKeyName(39, "C3M (39).png")
        Me.ImageCollection1.Images.SetKeyName(40, "C3M (40).png")
        Me.ImageCollection1.Images.SetKeyName(41, "C3M (41).png")
        Me.ImageCollection1.Images.SetKeyName(42, "C3M (42).png")
        Me.ImageCollection1.Images.SetKeyName(43, "C3M (43).png")
        Me.ImageCollection1.Images.SetKeyName(44, "C3M (44).png")
        Me.ImageCollection1.Images.SetKeyName(45, "C3M (45).png")
        Me.ImageCollection1.Images.SetKeyName(46, "C3M (46).png")
        Me.ImageCollection1.Images.SetKeyName(47, "C3M (47).png")
        Me.ImageCollection1.Images.SetKeyName(48, "C3M (48).png")
        Me.ImageCollection1.Images.SetKeyName(49, "C3M (49).png")
        Me.ImageCollection1.Images.SetKeyName(50, "C3M (50).png")
        Me.ImageCollection1.Images.SetKeyName(51, "C3M (51).png")
        Me.ImageCollection1.Images.SetKeyName(52, "C3M (52).png")
        Me.ImageCollection1.Images.SetKeyName(53, "C3M (53).png")
        Me.ImageCollection1.Images.SetKeyName(54, "C3M (54).png")
        Me.ImageCollection1.Images.SetKeyName(55, "C3M (55).png")
        Me.ImageCollection1.Images.SetKeyName(56, "C3M (56).png")
        Me.ImageCollection1.Images.SetKeyName(57, "C3M (57).png")
        Me.ImageCollection1.Images.SetKeyName(58, "C3M (58).png")
        Me.ImageCollection1.Images.SetKeyName(59, "C3M (59).png")
        Me.ImageCollection1.Images.SetKeyName(60, "C3M (60).png")
        Me.ImageCollection1.Images.SetKeyName(61, "C3M (61).png")
        Me.ImageCollection1.Images.SetKeyName(62, "C3M (62).png")
        Me.ImageCollection1.Images.SetKeyName(63, "C3M (63).png")
        Me.ImageCollection1.Images.SetKeyName(64, "C3M (64).png")
        Me.ImageCollection1.Images.SetKeyName(65, "C3M (65).png")
        Me.ImageCollection1.Images.SetKeyName(66, "C3M (66).png")
        Me.ImageCollection1.Images.SetKeyName(67, "C3M (67).png")
        Me.ImageCollection1.Images.SetKeyName(68, "C3M (68).png")
        Me.ImageCollection1.Images.SetKeyName(69, "C3M (69).png")
        Me.ImageCollection1.Images.SetKeyName(70, "C3M (70).png")
        Me.ImageCollection1.Images.SetKeyName(71, "C3M (71).png")
        Me.ImageCollection1.Images.SetKeyName(72, "C3M (72).png")
        Me.ImageCollection1.Images.SetKeyName(73, "C3M (73).png")
        Me.ImageCollection1.Images.SetKeyName(74, "C3M (74).png")
        Me.ImageCollection1.Images.SetKeyName(75, "C3M (75).png")
        Me.ImageCollection1.Images.SetKeyName(76, "C3M (76).png")
        Me.ImageCollection1.Images.SetKeyName(77, "C3M (77).png")
        Me.ImageCollection1.Images.SetKeyName(78, "C3M (78).png")
        Me.ImageCollection1.Images.SetKeyName(79, "C3M (79).png")
        Me.ImageCollection1.Images.SetKeyName(80, "C3M (80).png")
        Me.ImageCollection1.Images.SetKeyName(81, "C3M (81).png")
        Me.ImageCollection1.Images.SetKeyName(82, "C3M (82).png")
        Me.ImageCollection1.Images.SetKeyName(83, "C3M (83).png")
        Me.ImageCollection1.Images.SetKeyName(84, "C3M (84).png")
        Me.ImageCollection1.Images.SetKeyName(85, "C3M (85).png")
        Me.ImageCollection1.Images.SetKeyName(86, "C3M (86).png")
        Me.ImageCollection1.Images.SetKeyName(87, "C3M (87).png")
        Me.ImageCollection1.Images.SetKeyName(88, "C3M (88).png")
        Me.ImageCollection1.Images.SetKeyName(89, "C3M (89).png")
        Me.ImageCollection1.Images.SetKeyName(90, "C3M (90).png")
        Me.ImageCollection1.Images.SetKeyName(91, "C3M (91).png")
        Me.ImageCollection1.Images.SetKeyName(92, "C3M (92).png")
        Me.ImageCollection1.Images.SetKeyName(93, "C3M (93).png")
        Me.ImageCollection1.Images.SetKeyName(94, "C3M (94).png")
        Me.ImageCollection1.Images.SetKeyName(95, "C3M (95).png")
        Me.ImageCollection1.Images.SetKeyName(96, "C3M (96).png")
        Me.ImageCollection1.Images.SetKeyName(97, "C3M (97).png")
        Me.ImageCollection1.Images.SetKeyName(98, "C3M (98).png")
        Me.ImageCollection1.Images.SetKeyName(99, "C3M (99).png")
        Me.ImageCollection1.Images.SetKeyName(100, "C3M (100).png")
        Me.ImageCollection1.Images.SetKeyName(101, "C3M (101).png")
        Me.ImageCollection1.Images.SetKeyName(102, "C3M (102).png")
        Me.ImageCollection1.Images.SetKeyName(103, "C3M (103).png")
        Me.ImageCollection1.Images.SetKeyName(104, "C3M (104).png")
        Me.ImageCollection1.Images.SetKeyName(105, "C3M (105).png")
        Me.ImageCollection1.Images.SetKeyName(106, "C3M (106).png")
        Me.ImageCollection1.Images.SetKeyName(107, "C3M (107).png")
        Me.ImageCollection1.Images.SetKeyName(108, "C3M (108).png")
        Me.ImageCollection1.Images.SetKeyName(109, "C3M (109).png")
        Me.ImageCollection1.Images.SetKeyName(110, "C3M (110).png")
        Me.ImageCollection1.Images.SetKeyName(111, "C3M (111).png")
        Me.ImageCollection1.Images.SetKeyName(112, "C3M (112).png")
        Me.ImageCollection1.Images.SetKeyName(113, "C3M (113).png")
        Me.ImageCollection1.Images.SetKeyName(114, "C3M (114).png")
        Me.ImageCollection1.Images.SetKeyName(115, "C3M (115).png")
        Me.ImageCollection1.Images.SetKeyName(116, "C3M (116).png")
        Me.ImageCollection1.Images.SetKeyName(117, "C3M (117).png")
        Me.ImageCollection1.Images.SetKeyName(118, "C3M (118).png")
        Me.ImageCollection1.Images.SetKeyName(119, "C3M (119).png")
        Me.ImageCollection1.Images.SetKeyName(120, "C3M (120).png")
        Me.ImageCollection1.Images.SetKeyName(121, "C3M (121).png")
        Me.ImageCollection1.Images.SetKeyName(122, "C3M (122).png")
        Me.ImageCollection1.Images.SetKeyName(123, "C3M (123).png")
        Me.ImageCollection1.Images.SetKeyName(124, "C3M (124).png")
        Me.ImageCollection1.Images.SetKeyName(125, "C3M (125).png")
        Me.ImageCollection1.Images.SetKeyName(126, "C3M (126).png")
        Me.ImageCollection1.Images.SetKeyName(127, "C3M (127).png")
        Me.ImageCollection1.Images.SetKeyName(128, "C3M (128).png")
        Me.ImageCollection1.Images.SetKeyName(129, "C3M (129).png")
        Me.ImageCollection1.Images.SetKeyName(130, "C3M (130).png")
        Me.ImageCollection1.Images.SetKeyName(131, "C3M (131).png")
        Me.ImageCollection1.Images.SetKeyName(132, "C3M (132).png")
        Me.ImageCollection1.Images.SetKeyName(133, "C3M (133).png")
        Me.ImageCollection1.Images.SetKeyName(134, "C3M (134).png")
        Me.ImageCollection1.Images.SetKeyName(135, "C3M (135).png")
        Me.ImageCollection1.Images.SetKeyName(136, "C3M (136).png")
        Me.ImageCollection1.Images.SetKeyName(137, "C3M (137).png")
        Me.ImageCollection1.Images.SetKeyName(138, "C3M (138).png")
        Me.ImageCollection1.Images.SetKeyName(139, "C3M (139).png")
        Me.ImageCollection1.Images.SetKeyName(140, "C3M (140).png")
        Me.ImageCollection1.Images.SetKeyName(141, "C3M (141).png")
        Me.ImageCollection1.Images.SetKeyName(142, "C3M (142).png")
        Me.ImageCollection1.Images.SetKeyName(143, "C3M (143).png")
        Me.ImageCollection1.Images.SetKeyName(144, "C3M (144).png")
        Me.ImageCollection1.Images.SetKeyName(145, "C3M (145).png")
        Me.ImageCollection1.Images.SetKeyName(146, "C3M (146).png")
        Me.ImageCollection1.Images.SetKeyName(147, "C3M (147).png")
        Me.ImageCollection1.Images.SetKeyName(148, "C3M (148).png")
        Me.ImageCollection1.Images.SetKeyName(149, "C3M (149).png")
        Me.ImageCollection1.Images.SetKeyName(150, "C3M (150).png")
        Me.ImageCollection1.Images.SetKeyName(151, "C3M (151).png")
        Me.ImageCollection1.Images.SetKeyName(152, "C3M (152).png")
        Me.ImageCollection1.Images.SetKeyName(153, "C3M (153).png")
        Me.ImageCollection1.Images.SetKeyName(154, "C3M (154).png")
        Me.ImageCollection1.Images.SetKeyName(155, "C3M (155).png")
        Me.ImageCollection1.Images.SetKeyName(156, "C3M (156).png")
        Me.ImageCollection1.Images.SetKeyName(157, "C3M (157).png")
        Me.ImageCollection1.Images.SetKeyName(158, "C3M (158).png")
        Me.ImageCollection1.Images.SetKeyName(159, "C3M (159).png")
        Me.ImageCollection1.Images.SetKeyName(160, "C3M (160).png")
        Me.ImageCollection1.Images.SetKeyName(161, "C3M (161).png")
        Me.ImageCollection1.Images.SetKeyName(162, "C3M (162).png")
        Me.ImageCollection1.Images.SetKeyName(163, "C3M (163).png")
        Me.ImageCollection1.Images.SetKeyName(164, "C3M (164).png")
        Me.ImageCollection1.Images.SetKeyName(165, "C3M (165).png")
        Me.ImageCollection1.Images.SetKeyName(166, "C3M (166).png")
        Me.ImageCollection1.Images.SetKeyName(167, "C3M (167).png")
        Me.ImageCollection1.Images.SetKeyName(168, "C3M (168).png")
        Me.ImageCollection1.Images.SetKeyName(169, "C3M (169).png")
        Me.ImageCollection1.Images.SetKeyName(170, "C3M (170).png")
        Me.ImageCollection1.Images.SetKeyName(171, "C3M (171).png")
        Me.ImageCollection1.Images.SetKeyName(172, "C3M (172).png")
        Me.ImageCollection1.Images.SetKeyName(173, "C3M (173).png")
        Me.ImageCollection1.Images.SetKeyName(174, "C3M (174).png")
        Me.ImageCollection1.Images.SetKeyName(175, "C3M (175).png")
        Me.ImageCollection1.Images.SetKeyName(176, "C3M (176).png")
        Me.ImageCollection1.Images.SetKeyName(177, "C3M (177).png")
        Me.ImageCollection1.Images.SetKeyName(178, "C3M (178).png")
        Me.ImageCollection1.Images.SetKeyName(179, "C3M (179).png")
        Me.ImageCollection1.Images.SetKeyName(180, "C3M (180).png")
        Me.ImageCollection1.Images.SetKeyName(181, "C3M (181).png")
        Me.ImageCollection1.Images.SetKeyName(182, "C3M (182).png")
        Me.ImageCollection1.Images.SetKeyName(183, "C3M (183).png")
        Me.ImageCollection1.Images.SetKeyName(184, "C3M (184).png")
        Me.ImageCollection1.Images.SetKeyName(185, "C3M (185).png")
        Me.ImageCollection1.Images.SetKeyName(186, "C3M (186).png")
        Me.ImageCollection1.Images.SetKeyName(187, "C3M (187).png")
        Me.ImageCollection1.Images.SetKeyName(188, "C3M (188).png")
        Me.ImageCollection1.Images.SetKeyName(189, "C3M (189).png")
        Me.ImageCollection1.Images.SetKeyName(190, "C3M (190).png")
        Me.ImageCollection1.Images.SetKeyName(191, "C3M (191).png")
        Me.ImageCollection1.Images.SetKeyName(192, "C3M (192).png")
        Me.ImageCollection1.Images.SetKeyName(193, "C3M (193).png")
        Me.ImageCollection1.Images.SetKeyName(194, "C3M (194).png")
        Me.ImageCollection1.Images.SetKeyName(195, "C3M (195).png")
        Me.ImageCollection1.Images.SetKeyName(196, "C3M (196).png")
        Me.ImageCollection1.Images.SetKeyName(197, "C3M (197).png")
        Me.ImageCollection1.Images.SetKeyName(198, "C3M (198).png")
        Me.ImageCollection1.Images.SetKeyName(199, "C3M (199).png")
        Me.ImageCollection1.Images.SetKeyName(200, "C3M (200).png")
        Me.ImageCollection1.Images.SetKeyName(201, "C3M (201).png")
        Me.ImageCollection1.Images.SetKeyName(202, "C3M (202).png")
        Me.ImageCollection1.Images.SetKeyName(203, "C3M (203).png")
        Me.ImageCollection1.Images.SetKeyName(204, "C3M (204).png")
        Me.ImageCollection1.Images.SetKeyName(205, "C3M (205).png")
        Me.ImageCollection1.Images.SetKeyName(206, "C3M (206).png")
        Me.ImageCollection1.Images.SetKeyName(207, "C3M (207).png")
        Me.ImageCollection1.Images.SetKeyName(208, "C3M (208).png")
        Me.ImageCollection1.Images.SetKeyName(209, "C3M (209).png")
        Me.ImageCollection1.Images.SetKeyName(210, "C3M (210).png")
        Me.ImageCollection1.Images.SetKeyName(211, "C3M (211).png")
        Me.ImageCollection1.Images.SetKeyName(212, "C3M (212).png")
        Me.ImageCollection1.Images.SetKeyName(213, "C3M (213).png")
        Me.ImageCollection1.Images.SetKeyName(214, "C3M (214).png")
        Me.ImageCollection1.Images.SetKeyName(215, "C3M (215).png")
        Me.ImageCollection1.Images.SetKeyName(216, "C3M (216).png")
        Me.ImageCollection1.Images.SetKeyName(217, "C3M (217).png")
        Me.ImageCollection1.Images.SetKeyName(218, "C3M (218).png")
        Me.ImageCollection1.Images.SetKeyName(219, "C3M (219).png")
        Me.ImageCollection1.Images.SetKeyName(220, "C3M (220).png")
        Me.ImageCollection1.Images.SetKeyName(221, "C3M (221).png")
        Me.ImageCollection1.Images.SetKeyName(222, "C3M (222).png")
        Me.ImageCollection1.Images.SetKeyName(223, "C3M (223).png")
        Me.ImageCollection1.Images.SetKeyName(224, "C3M (224).png")
        Me.ImageCollection1.Images.SetKeyName(225, "C3M (225).png")
        Me.ImageCollection1.Images.SetKeyName(226, "C3M (226).png")
        Me.ImageCollection1.Images.SetKeyName(227, "C3M (227).png")
        Me.ImageCollection1.Images.SetKeyName(228, "C3M (228).png")
        Me.ImageCollection1.Images.SetKeyName(229, "C3M (229).png")
        Me.ImageCollection1.Images.SetKeyName(230, "C3M (230).png")
        Me.ImageCollection1.Images.SetKeyName(231, "C3M (231).png")
        Me.ImageCollection1.Images.SetKeyName(232, "C3M (232).png")
        Me.ImageCollection1.Images.SetKeyName(233, "C3M (233).png")
        Me.ImageCollection1.Images.SetKeyName(234, "C3M (234).png")
        Me.ImageCollection1.Images.SetKeyName(235, "C3M (235).png")
        Me.ImageCollection1.Images.SetKeyName(236, "C3M (236).png")
        Me.ImageCollection1.Images.SetKeyName(237, "C3M (237).png")
        Me.ImageCollection1.Images.SetKeyName(238, "C3M (238).png")
        Me.ImageCollection1.Images.SetKeyName(239, "C3M (239).png")
        Me.ImageCollection1.Images.SetKeyName(240, "C3M (240).png")
        Me.ImageCollection1.Images.SetKeyName(241, "C3M (241).png")
        Me.ImageCollection1.Images.SetKeyName(242, "C3M (242).png")
        Me.ImageCollection1.Images.SetKeyName(243, "C3M (243).png")
        Me.ImageCollection1.Images.SetKeyName(244, "C3M (244).png")
        Me.ImageCollection1.Images.SetKeyName(245, "C3M (245).png")
        Me.ImageCollection1.Images.SetKeyName(246, "C3M (246).png")
        Me.ImageCollection1.Images.SetKeyName(247, "C3M (247).png")
        Me.ImageCollection1.Images.SetKeyName(248, "C3M (248).png")
        Me.ImageCollection1.Images.SetKeyName(249, "C3M (249).png")
        Me.ImageCollection1.Images.SetKeyName(250, "C3M (250).png")
        Me.ImageCollection1.Images.SetKeyName(251, "C3M (251).png")
        Me.ImageCollection1.Images.SetKeyName(252, "C3M (252).png")
        Me.ImageCollection1.Images.SetKeyName(253, "C3M (253).png")
        Me.ImageCollection1.Images.SetKeyName(254, "C3M (254).png")
        Me.ImageCollection1.Images.SetKeyName(255, "C3M (255).png")
        Me.ImageCollection1.Images.SetKeyName(256, "C3M (256).png")
        Me.ImageCollection1.Images.SetKeyName(257, "C3M (257).png")
        Me.ImageCollection1.Images.SetKeyName(258, "C3M (258).png")
        Me.ImageCollection1.Images.SetKeyName(259, "C3M (259).png")
        Me.ImageCollection1.Images.SetKeyName(260, "C3M (260).png")
        Me.ImageCollection1.Images.SetKeyName(261, "C3M (261).png")
        Me.ImageCollection1.Images.SetKeyName(262, "C3M (262).png")
        Me.ImageCollection1.Images.SetKeyName(263, "C3M (263).png")
        Me.ImageCollection1.Images.SetKeyName(264, "C3M (264).png")
        Me.ImageCollection1.Images.SetKeyName(265, "C3M (265).png")
        Me.ImageCollection1.Images.SetKeyName(266, "C3M (266).png")
        Me.ImageCollection1.Images.SetKeyName(267, "C3M (267).png")
        Me.ImageCollection1.Images.SetKeyName(268, "C3M (268).png")
        Me.ImageCollection1.Images.SetKeyName(269, "C3M (269).png")
        Me.ImageCollection1.Images.SetKeyName(270, "C3M (270).png")
        Me.ImageCollection1.Images.SetKeyName(271, "C3M (271).png")
        Me.ImageCollection1.Images.SetKeyName(272, "C3M (272).png")
        Me.ImageCollection1.Images.SetKeyName(273, "C3M (273).png")
        Me.ImageCollection1.Images.SetKeyName(274, "C3M (274).png")
        Me.ImageCollection1.Images.SetKeyName(275, "C3M (275).png")
        Me.ImageCollection1.Images.SetKeyName(276, "C3M (276).png")
        Me.ImageCollection1.Images.SetKeyName(277, "C3M (277).png")
        Me.ImageCollection1.Images.SetKeyName(278, "C3M (278).png")
        Me.ImageCollection1.Images.SetKeyName(279, "C3M (279).png")
        Me.ImageCollection1.Images.SetKeyName(280, "C3M (280).png")
        Me.ImageCollection1.Images.SetKeyName(281, "C3M (281).png")
        Me.ImageCollection1.Images.SetKeyName(282, "C3M (282).png")
        Me.ImageCollection1.Images.SetKeyName(283, "C3M (283).png")
        Me.ImageCollection1.Images.SetKeyName(284, "C3M (284).png")
        Me.ImageCollection1.Images.SetKeyName(285, "C3M (285).png")
        Me.ImageCollection1.Images.SetKeyName(286, "C3M (286).png")
        Me.ImageCollection1.Images.SetKeyName(287, "C3M (287).png")
        Me.ImageCollection1.Images.SetKeyName(288, "C3M (288).png")
        Me.ImageCollection1.Images.SetKeyName(289, "C3M (289).png")
        Me.ImageCollection1.Images.SetKeyName(290, "C3M (290).png")
        Me.ImageCollection1.Images.SetKeyName(291, "C3M (291).png")
        Me.ImageCollection1.Images.SetKeyName(292, "C3M (292).png")
        Me.ImageCollection1.Images.SetKeyName(293, "C3M (293).png")
        Me.ImageCollection1.Images.SetKeyName(294, "C3M (294).png")
        Me.ImageCollection1.Images.SetKeyName(295, "C3M (295).png")
        Me.ImageCollection1.Images.SetKeyName(296, "C3M (296).png")
        Me.ImageCollection1.Images.SetKeyName(297, "C3M (297).png")
        Me.ImageCollection1.Images.SetKeyName(298, "C3M (298).png")
        Me.ImageCollection1.Images.SetKeyName(299, "C3M (299).png")
        Me.ImageCollection1.Images.SetKeyName(300, "C3M (300).png")
        Me.ImageCollection1.Images.SetKeyName(301, "C3M (301).png")
        Me.ImageCollection1.Images.SetKeyName(302, "C3M (302).png")
        Me.ImageCollection1.Images.SetKeyName(303, "C3M (303).png")
        Me.ImageCollection1.Images.SetKeyName(304, "C3M (304).png")
        Me.ImageCollection1.Images.SetKeyName(305, "C3M (305).png")
        Me.ImageCollection1.Images.SetKeyName(306, "C3M (306).png")
        Me.ImageCollection1.Images.SetKeyName(307, "C3M (307).png")
        Me.ImageCollection1.Images.SetKeyName(308, "C3M (308).png")
        Me.ImageCollection1.Images.SetKeyName(309, "C3M (309).png")
        Me.ImageCollection1.Images.SetKeyName(310, "C3M (310).png")
        Me.ImageCollection1.Images.SetKeyName(311, "C3M (311).png")
        Me.ImageCollection1.Images.SetKeyName(312, "C3M (312).png")
        Me.ImageCollection1.Images.SetKeyName(313, "C3M (313).png")
        Me.ImageCollection1.Images.SetKeyName(314, "C3M (314).png")
        Me.ImageCollection1.Images.SetKeyName(315, "C3M (315).png")
        Me.ImageCollection1.Images.SetKeyName(316, "C3M (316).png")
        Me.ImageCollection1.Images.SetKeyName(317, "C3M (317).png")
        Me.ImageCollection1.Images.SetKeyName(318, "C3M (318).png")
        Me.ImageCollection1.Images.SetKeyName(319, "C3M (319).png")
        Me.ImageCollection1.Images.SetKeyName(320, "C3M (320).png")
        Me.ImageCollection1.Images.SetKeyName(321, "C3M (321).png")
        Me.ImageCollection1.Images.SetKeyName(322, "C3M (322).png")
        Me.ImageCollection1.Images.SetKeyName(323, "C3M (323).png")
        Me.ImageCollection1.Images.SetKeyName(324, "C3M (324).png")
        Me.ImageCollection1.Images.SetKeyName(325, "C3M (325).png")
        Me.ImageCollection1.Images.SetKeyName(326, "C3M (326).png")
        Me.ImageCollection1.Images.SetKeyName(327, "C3M (327).png")
        Me.ImageCollection1.Images.SetKeyName(328, "C3M (328).png")
        Me.ImageCollection1.Images.SetKeyName(329, "C3M (329).png")
        Me.ImageCollection1.Images.SetKeyName(330, "C3M (330).png")
        Me.ImageCollection1.Images.SetKeyName(331, "C3M (331).png")
        Me.ImageCollection1.Images.SetKeyName(332, "C3M (332).png")
        Me.ImageCollection1.Images.SetKeyName(333, "C3M (333).png")
        Me.ImageCollection1.Images.SetKeyName(334, "C3M (334).png")
        Me.ImageCollection1.Images.SetKeyName(335, "C3M (335).png")
        Me.ImageCollection1.Images.SetKeyName(336, "C3M (336).png")
        Me.ImageCollection1.Images.SetKeyName(337, "C3M (337).png")
        Me.ImageCollection1.Images.SetKeyName(338, "C3M (338).png")
        Me.ImageCollection1.Images.SetKeyName(339, "C3M (339).png")
        Me.ImageCollection1.Images.SetKeyName(340, "C3M (340).png")
        Me.ImageCollection1.Images.SetKeyName(341, "C3M (341).png")
        Me.ImageCollection1.Images.SetKeyName(342, "C3M (342).png")
        Me.ImageCollection1.Images.SetKeyName(343, "C3M (343).png")
        Me.ImageCollection1.Images.SetKeyName(344, "C3M (344).png")
        Me.ImageCollection1.Images.SetKeyName(345, "C3M (345).png")
        Me.ImageCollection1.Images.SetKeyName(346, "C3M (346).png")
        Me.ImageCollection1.Images.SetKeyName(347, "C3M (347).png")
        Me.ImageCollection1.Images.SetKeyName(348, "C3M (348).png")
        Me.ImageCollection1.Images.SetKeyName(349, "C3M (349).png")
        Me.ImageCollection1.Images.SetKeyName(350, "C3M (350).png")
        Me.ImageCollection1.Images.SetKeyName(351, "C3M (351).png")
        Me.ImageCollection1.Images.SetKeyName(352, "C3M (352).png")
        Me.ImageCollection1.Images.SetKeyName(353, "C3M (353).png")
        Me.ImageCollection1.Images.SetKeyName(354, "C3M (354).png")
        Me.ImageCollection1.Images.SetKeyName(355, "C3M (355).png")
        Me.ImageCollection1.Images.SetKeyName(356, "C3M (356).png")
        Me.ImageCollection1.Images.SetKeyName(357, "C3M (357).png")
        Me.ImageCollection1.Images.SetKeyName(358, "C3M (358).png")
        Me.ImageCollection1.Images.SetKeyName(359, "C3M (359).png")
        Me.ImageCollection1.Images.SetKeyName(360, "C3M (360).png")
        Me.ImageCollection1.Images.SetKeyName(361, "C3M (361).png")
        Me.ImageCollection1.Images.SetKeyName(362, "C3M (362).png")
        Me.ImageCollection1.Images.SetKeyName(363, "C3M (363).png")
        Me.ImageCollection1.Images.SetKeyName(364, "C3M (364).png")
        Me.ImageCollection1.Images.SetKeyName(365, "C3M (365).png")
        Me.ImageCollection1.Images.SetKeyName(366, "C3M (366).png")
        Me.ImageCollection1.Images.SetKeyName(367, "C3M (367).png")
        Me.ImageCollection1.Images.SetKeyName(368, "C3M (368).png")
        Me.ImageCollection1.Images.SetKeyName(369, "C3M (369).png")
        Me.ImageCollection1.Images.SetKeyName(370, "C3M (370).png")
        Me.ImageCollection1.Images.SetKeyName(371, "C3M (371).png")
        Me.ImageCollection1.Images.SetKeyName(372, "C3M (372).png")
        Me.ImageCollection1.Images.SetKeyName(373, "C3M (373).png")
        Me.ImageCollection1.Images.SetKeyName(374, "C3M (374).png")
        Me.ImageCollection1.Images.SetKeyName(375, "C3M (375).png")
        Me.ImageCollection1.Images.SetKeyName(376, "C3M (376).png")
        Me.ImageCollection1.Images.SetKeyName(377, "C3M (377).png")
        Me.ImageCollection1.Images.SetKeyName(378, "C3M (378).png")
        Me.ImageCollection1.Images.SetKeyName(379, "C3M (379).png")
        Me.ImageCollection1.Images.SetKeyName(380, "C3M (380).png")
        Me.ImageCollection1.Images.SetKeyName(381, "C3M (381).png")
        Me.ImageCollection1.Images.SetKeyName(382, "C3M (382).png")
        Me.ImageCollection1.Images.SetKeyName(383, "C3M (383).png")
        Me.ImageCollection1.Images.SetKeyName(384, "C3M (384).png")
        Me.ImageCollection1.Images.SetKeyName(385, "C3M (385).png")
        Me.ImageCollection1.Images.SetKeyName(386, "C3M (386).png")
        Me.ImageCollection1.Images.SetKeyName(387, "C3M (387).png")
        Me.ImageCollection1.Images.SetKeyName(388, "C3M (388).png")
        Me.ImageCollection1.Images.SetKeyName(389, "C3M (389).png")
        Me.ImageCollection1.Images.SetKeyName(390, "C3M (390).png")
        Me.ImageCollection1.Images.SetKeyName(391, "C3M (391).png")
        Me.ImageCollection1.Images.SetKeyName(392, "C3M (392).png")
        Me.ImageCollection1.Images.SetKeyName(393, "C3M (393).png")
        Me.ImageCollection1.Images.SetKeyName(394, "C3M (394).png")
        Me.ImageCollection1.Images.SetKeyName(395, "C3M (395).png")
        Me.ImageCollection1.Images.SetKeyName(396, "C3M (396).png")
        Me.ImageCollection1.Images.SetKeyName(397, "C3M (397).png")
        Me.ImageCollection1.Images.SetKeyName(398, "C3M (398).png")
        Me.ImageCollection1.Images.SetKeyName(399, "C3M (399).png")
        Me.ImageCollection1.Images.SetKeyName(400, "C3M (400).png")
        Me.ImageCollection1.Images.SetKeyName(401, "C3M (401).png")
        Me.ImageCollection1.Images.SetKeyName(402, "C3M (402).png")
        Me.ImageCollection1.Images.SetKeyName(403, "C3M (403).png")
        Me.ImageCollection1.Images.SetKeyName(404, "C3M (404).png")
        Me.ImageCollection1.Images.SetKeyName(405, "C3M (405).png")
        Me.ImageCollection1.Images.SetKeyName(406, "C3M (406).png")
        Me.ImageCollection1.Images.SetKeyName(407, "C3M (407).png")
        Me.ImageCollection1.Images.SetKeyName(408, "C3M (408).png")
        Me.ImageCollection1.Images.SetKeyName(409, "C3M (409).png")
        Me.ImageCollection1.Images.SetKeyName(410, "C3M (410).png")
        Me.ImageCollection1.Images.SetKeyName(411, "C3M (411).png")
        Me.ImageCollection1.Images.SetKeyName(412, "C3M (412).png")
        Me.ImageCollection1.Images.SetKeyName(413, "C3M (413).png")
        Me.ImageCollection1.Images.SetKeyName(414, "C3M (414).png")
        Me.ImageCollection1.Images.SetKeyName(415, "C3M (415).png")
        Me.ImageCollection1.Images.SetKeyName(416, "C3M (416).png")
        Me.ImageCollection1.Images.SetKeyName(417, "C3M (417).png")
        Me.ImageCollection1.Images.SetKeyName(418, "C3M (418).png")
        Me.ImageCollection1.Images.SetKeyName(419, "C3M (419).png")
        Me.ImageCollection1.Images.SetKeyName(420, "C3M (420).png")
        Me.ImageCollection1.Images.SetKeyName(421, "C3M (421).png")
        Me.ImageCollection1.Images.SetKeyName(422, "C3M (422).png")
        Me.ImageCollection1.Images.SetKeyName(423, "C3M (423).png")
        Me.ImageCollection1.Images.SetKeyName(424, "C3M (424).png")
        Me.ImageCollection1.Images.SetKeyName(425, "C3M (425).png")
        Me.ImageCollection1.Images.SetKeyName(426, "C3M (426).png")
        Me.ImageCollection1.Images.SetKeyName(427, "C3M (427).png")
        Me.ImageCollection1.Images.SetKeyName(428, "C3M (428).png")
        Me.ImageCollection1.Images.SetKeyName(429, "C3M (429).png")
        Me.ImageCollection1.Images.SetKeyName(430, "C3M (430).png")
        Me.ImageCollection1.Images.SetKeyName(431, "C3M (431).png")
        Me.ImageCollection1.Images.SetKeyName(432, "C3M (432).png")
        Me.ImageCollection1.Images.SetKeyName(433, "C3M (433).png")
        Me.ImageCollection1.Images.SetKeyName(434, "C3M (434).png")
        Me.ImageCollection1.Images.SetKeyName(435, "C3M (435).png")
        Me.ImageCollection1.Images.SetKeyName(436, "C3M (436).png")
        Me.ImageCollection1.Images.SetKeyName(437, "C3M (437).png")
        Me.ImageCollection1.Images.SetKeyName(438, "C3M (438).png")
        Me.ImageCollection1.Images.SetKeyName(439, "C3M (439).png")
        Me.ImageCollection1.Images.SetKeyName(440, "C3M (440).png")
        Me.ImageCollection1.Images.SetKeyName(441, "C3M (441).png")
        Me.ImageCollection1.Images.SetKeyName(442, "C3M (442).png")
        Me.ImageCollection1.Images.SetKeyName(443, "C3M (443).png")
        Me.ImageCollection1.Images.SetKeyName(444, "C3M (444).png")
        Me.ImageCollection1.Images.SetKeyName(445, "C3M (445).png")
        Me.ImageCollection1.Images.SetKeyName(446, "C3M (446).png")
        Me.ImageCollection1.Images.SetKeyName(447, "C3M (447).png")
        Me.ImageCollection1.Images.SetKeyName(448, "C3M (448).png")
        Me.ImageCollection1.Images.SetKeyName(449, "C3M (449).png")
        Me.ImageCollection1.Images.SetKeyName(450, "C3M (450).png")
        Me.ImageCollection1.Images.SetKeyName(451, "C3M (451).png")
        Me.ImageCollection1.Images.SetKeyName(452, "C3M (452).png")
        Me.ImageCollection1.Images.SetKeyName(453, "C3M (453).png")
        Me.ImageCollection1.Images.SetKeyName(454, "C3M (454).png")
        Me.ImageCollection1.Images.SetKeyName(455, "C3M (455).png")
        Me.ImageCollection1.Images.SetKeyName(456, "C3M (456).png")
        Me.ImageCollection1.Images.SetKeyName(457, "C3M (457).png")
        Me.ImageCollection1.Images.SetKeyName(458, "C3M (458).png")
        Me.ImageCollection1.Images.SetKeyName(459, "C3M (459).png")
        Me.ImageCollection1.Images.SetKeyName(460, "C3M (460).png")
        Me.ImageCollection1.Images.SetKeyName(461, "C3M (461).png")
        Me.ImageCollection1.Images.SetKeyName(462, "C3M (462).png")
        Me.ImageCollection1.Images.SetKeyName(463, "C3M (463).png")
        Me.ImageCollection1.Images.SetKeyName(464, "C3M (464).png")
        Me.ImageCollection1.Images.SetKeyName(465, "C3M (465).png")
        Me.ImageCollection1.Images.SetKeyName(466, "C3M (466).png")
        Me.ImageCollection1.Images.SetKeyName(467, "C3M (467).png")
        Me.ImageCollection1.Images.SetKeyName(468, "C3M (468).png")
        Me.ImageCollection1.Images.SetKeyName(469, "C3M (469).png")
        Me.ImageCollection1.Images.SetKeyName(470, "C3M (470).png")
        Me.ImageCollection1.Images.SetKeyName(471, "C3M (471).png")
        Me.ImageCollection1.Images.SetKeyName(472, "C3M (472).png")
        Me.ImageCollection1.Images.SetKeyName(473, "C3M (473).png")
        Me.ImageCollection1.Images.SetKeyName(474, "C3M (474).png")
        Me.ImageCollection1.Images.SetKeyName(475, "C3M (475).png")
        Me.ImageCollection1.Images.SetKeyName(476, "C3M (476).png")
        Me.ImageCollection1.Images.SetKeyName(477, "C3M (477).png")
        Me.ImageCollection1.Images.SetKeyName(478, "C3M (478).png")
        Me.ImageCollection1.Images.SetKeyName(479, "C3M (479).png")
        Me.ImageCollection1.Images.SetKeyName(480, "C3M (480).png")
        Me.ImageCollection1.Images.SetKeyName(481, "C3M (481).png")
        Me.ImageCollection1.Images.SetKeyName(482, "C3M (482).png")
        Me.ImageCollection1.Images.SetKeyName(483, "C3M (483).png")
        Me.ImageCollection1.Images.SetKeyName(484, "C3M (484).png")
        Me.ImageCollection1.Images.SetKeyName(485, "C3M (485).png")
        Me.ImageCollection1.Images.SetKeyName(486, "C3M (486).png")
        Me.ImageCollection1.Images.SetKeyName(487, "C3M (487).png")
        Me.ImageCollection1.Images.SetKeyName(488, "C3M (488).png")
        Me.ImageCollection1.Images.SetKeyName(489, "C3M (489).png")
        Me.ImageCollection1.Images.SetKeyName(490, "C3M (490).png")
        Me.ImageCollection1.Images.SetKeyName(491, "C3M (491).png")
        Me.ImageCollection1.Images.SetKeyName(492, "C3M (492).png")
        Me.ImageCollection1.Images.SetKeyName(493, "C3M (493).png")
        Me.ImageCollection1.Images.SetKeyName(494, "C3M (494).png")
        Me.ImageCollection1.Images.SetKeyName(495, "C3M (495).png")
        Me.ImageCollection1.Images.SetKeyName(496, "C3M (496).png")
        Me.ImageCollection1.Images.SetKeyName(497, "C3M (497).png")
        Me.ImageCollection1.Images.SetKeyName(498, "C3M (498).png")
        Me.ImageCollection1.Images.SetKeyName(499, "C3M (499).png")
        Me.ImageCollection1.Images.SetKeyName(500, "C3M (500).png")
        Me.ImageCollection1.Images.SetKeyName(501, "C3M (501).png")
        Me.ImageCollection1.Images.SetKeyName(502, "C3M (502).png")
        Me.ImageCollection1.Images.SetKeyName(503, "C3M (503).png")
        Me.ImageCollection1.Images.SetKeyName(504, "C3M (504).png")
        Me.ImageCollection1.Images.SetKeyName(505, "C3M (505).png")
        Me.ImageCollection1.Images.SetKeyName(506, "C3M (506).png")
        Me.ImageCollection1.Images.SetKeyName(507, "C3M (507).png")
        Me.ImageCollection1.Images.SetKeyName(508, "C3M (508).png")
        Me.ImageCollection1.Images.SetKeyName(509, "C3M (509).png")
        Me.ImageCollection1.Images.SetKeyName(510, "C3M (510).png")
        Me.ImageCollection1.Images.SetKeyName(511, "C3M (511).png")
        Me.ImageCollection1.Images.SetKeyName(512, "C3M (512).png")
        Me.ImageCollection1.Images.SetKeyName(513, "C3M (513).png")
        Me.ImageCollection1.Images.SetKeyName(514, "C3M (514).png")
        Me.ImageCollection1.Images.SetKeyName(515, "C3M (515).png")
        Me.ImageCollection1.Images.SetKeyName(516, "C3M (516).png")
        Me.ImageCollection1.Images.SetKeyName(517, "C3M (517).png")
        Me.ImageCollection1.Images.SetKeyName(518, "C3M (518).png")
        Me.ImageCollection1.Images.SetKeyName(519, "C3M (519).png")
        Me.ImageCollection1.Images.SetKeyName(520, "C3M (520).png")
        Me.ImageCollection1.Images.SetKeyName(521, "C3M (521).png")
        Me.ImageCollection1.Images.SetKeyName(522, "C3M (522).png")
        Me.ImageCollection1.Images.SetKeyName(523, "C3M (523).png")
        Me.ImageCollection1.Images.SetKeyName(524, "C3M (524).png")
        Me.ImageCollection1.Images.SetKeyName(525, "C3M (525).png")
        Me.ImageCollection1.Images.SetKeyName(526, "C3M (526).png")
        Me.ImageCollection1.Images.SetKeyName(527, "C3M (527).png")
        Me.ImageCollection1.Images.SetKeyName(528, "C3M (528).png")
        Me.ImageCollection1.Images.SetKeyName(529, "C3M (529).png")
        Me.ImageCollection1.Images.SetKeyName(530, "C3M (530).png")
        Me.ImageCollection1.Images.SetKeyName(531, "C3M (531).png")
        Me.ImageCollection1.Images.SetKeyName(532, "C3M (532).png")
        Me.ImageCollection1.Images.SetKeyName(533, "C3M (533).png")
        Me.ImageCollection1.Images.SetKeyName(534, "C3M (534).png")
        Me.ImageCollection1.Images.SetKeyName(535, "C3M (535).png")
        Me.ImageCollection1.Images.SetKeyName(536, "C3M (536).png")
        Me.ImageCollection1.Images.SetKeyName(537, "C3M (537).png")
        Me.ImageCollection1.Images.SetKeyName(538, "C3M (538).png")
        Me.ImageCollection1.Images.SetKeyName(539, "C3M (539).png")
        Me.ImageCollection1.Images.SetKeyName(540, "C3M (540).png")
        Me.ImageCollection1.Images.SetKeyName(541, "C3M (541).png")
        Me.ImageCollection1.Images.SetKeyName(542, "C3M (542).png")
        Me.ImageCollection1.Images.SetKeyName(543, "C3M (543).png")
        Me.ImageCollection1.Images.SetKeyName(544, "C3M (544).png")
        Me.ImageCollection1.Images.SetKeyName(545, "C3M (545).png")
        Me.ImageCollection1.Images.SetKeyName(546, "C3M (546).png")
        Me.ImageCollection1.Images.SetKeyName(547, "C3M (547).png")
        Me.ImageCollection1.Images.SetKeyName(548, "C3M (548).png")
        Me.ImageCollection1.Images.SetKeyName(549, "C3M (549).png")
        Me.ImageCollection1.Images.SetKeyName(550, "C3M (550).png")
        Me.ImageCollection1.Images.SetKeyName(551, "C3M (551).png")
        Me.ImageCollection1.Images.SetKeyName(552, "C3M (552).png")
        Me.ImageCollection1.Images.SetKeyName(553, "C3M (553).png")
        Me.ImageCollection1.Images.SetKeyName(554, "C3M (554).png")
        Me.ImageCollection1.Images.SetKeyName(555, "C3M (555).png")
        Me.ImageCollection1.Images.SetKeyName(556, "C3M (556).png")
        Me.ImageCollection1.Images.SetKeyName(557, "C3M (557).png")
        Me.ImageCollection1.Images.SetKeyName(558, "C3M (558).png")
        Me.ImageCollection1.Images.SetKeyName(559, "C3M (559).png")
        Me.ImageCollection1.Images.SetKeyName(560, "C3M (560).png")
        Me.ImageCollection1.Images.SetKeyName(561, "C3M (561).png")
        Me.ImageCollection1.Images.SetKeyName(562, "C3M (562).png")
        Me.ImageCollection1.Images.SetKeyName(563, "C3M (563).png")
        Me.ImageCollection1.Images.SetKeyName(564, "C3M (564).png")
        Me.ImageCollection1.Images.SetKeyName(565, "C3M (565).png")
        Me.ImageCollection1.Images.SetKeyName(566, "C3M (566).png")
        Me.ImageCollection1.Images.SetKeyName(567, "C3M (567).png")
        Me.ImageCollection1.Images.SetKeyName(568, "C3M (568).png")
        Me.ImageCollection1.Images.SetKeyName(569, "C3M (569).png")
        Me.ImageCollection1.Images.SetKeyName(570, "C3M (570).png")
        Me.ImageCollection1.Images.SetKeyName(571, "C3M (571).png")
        Me.ImageCollection1.Images.SetKeyName(572, "C3M (572).png")
        Me.ImageCollection1.Images.SetKeyName(573, "C3M (573).png")
        Me.ImageCollection1.Images.SetKeyName(574, "C3M (574).png")
        Me.ImageCollection1.Images.SetKeyName(575, "C3M (575).png")
        Me.ImageCollection1.Images.SetKeyName(576, "C3M (576).png")
        Me.ImageCollection1.Images.SetKeyName(577, "C3M (577).png")
        Me.ImageCollection1.Images.SetKeyName(578, "C3M (578).png")
        Me.ImageCollection1.Images.SetKeyName(579, "C3M (579).png")
        Me.ImageCollection1.Images.SetKeyName(580, "C3M (580).png")
        Me.ImageCollection1.Images.SetKeyName(581, "C3M (581).png")
        Me.ImageCollection1.Images.SetKeyName(582, "C3M (582).png")
        Me.ImageCollection1.Images.SetKeyName(583, "C3M (583).png")
        Me.ImageCollection1.Images.SetKeyName(584, "C3M (584).png")
        Me.ImageCollection1.Images.SetKeyName(585, "C3M (585).png")
        Me.ImageCollection1.Images.SetKeyName(586, "C3M (586).png")
        Me.ImageCollection1.Images.SetKeyName(587, "C3M (587).png")
        Me.ImageCollection1.Images.SetKeyName(588, "C3M (588).png")
        Me.ImageCollection1.Images.SetKeyName(589, "C3M (589).png")
        Me.ImageCollection1.Images.SetKeyName(590, "C3M (590).png")
        Me.ImageCollection1.Images.SetKeyName(591, "C3M (591).png")
        Me.ImageCollection1.Images.SetKeyName(592, "C3M (592).png")
        Me.ImageCollection1.Images.SetKeyName(593, "C3M (593).png")
        Me.ImageCollection1.Images.SetKeyName(594, "C3M (594).png")
        Me.ImageCollection1.Images.SetKeyName(595, "C3M (595).png")
        Me.ImageCollection1.Images.SetKeyName(596, "C3M (596).png")
        Me.ImageCollection1.Images.SetKeyName(597, "C3M (597).png")
        Me.ImageCollection1.Images.SetKeyName(598, "C3M (598).png")
        Me.ImageCollection1.Images.SetKeyName(599, "C3M (599).png")
        Me.ImageCollection1.Images.SetKeyName(600, "C3M (600).png")
        Me.ImageCollection1.Images.SetKeyName(601, "C3M (601).png")
        Me.ImageCollection1.Images.SetKeyName(602, "C3M (602).png")
        Me.ImageCollection1.Images.SetKeyName(603, "C3M (603).png")
        Me.ImageCollection1.Images.SetKeyName(604, "C3M (604).png")
        Me.ImageCollection1.Images.SetKeyName(605, "C3M (605).png")
        Me.ImageCollection1.Images.SetKeyName(606, "C3M (606).png")
        Me.ImageCollection1.Images.SetKeyName(607, "C3M (607).png")
        Me.ImageCollection1.Images.SetKeyName(608, "C3M (608).png")
        Me.ImageCollection1.Images.SetKeyName(609, "C3M (609).png")
        Me.ImageCollection1.Images.SetKeyName(610, "C3M (610).png")
        Me.ImageCollection1.Images.SetKeyName(611, "C3M (611).png")
        Me.ImageCollection1.Images.SetKeyName(612, "C3M (612).png")
        Me.ImageCollection1.Images.SetKeyName(613, "C3M (613).png")
        Me.ImageCollection1.Images.SetKeyName(614, "C3M (614).png")
        Me.ImageCollection1.Images.SetKeyName(615, "C3M (615).png")
        Me.ImageCollection1.Images.SetKeyName(616, "C3M (616).png")
        Me.ImageCollection1.Images.SetKeyName(617, "C3M (617).png")
        Me.ImageCollection1.Images.SetKeyName(618, "C3M (618).png")
        Me.ImageCollection1.Images.SetKeyName(619, "C3M (619).png")
        Me.ImageCollection1.Images.SetKeyName(620, "C3M (620).png")
        Me.ImageCollection1.Images.SetKeyName(621, "C3M (621).png")
        Me.ImageCollection1.Images.SetKeyName(622, "C3M (622).png")
        Me.ImageCollection1.Images.SetKeyName(623, "C3M (623).png")
        Me.ImageCollection1.Images.SetKeyName(624, "C3M (624).png")
        Me.ImageCollection1.Images.SetKeyName(625, "C3M (625).png")
        Me.ImageCollection1.Images.SetKeyName(626, "C3M (626).png")
        Me.ImageCollection1.Images.SetKeyName(627, "C3M (627).png")
        Me.ImageCollection1.Images.SetKeyName(628, "C3M (628).png")
        Me.ImageCollection1.Images.SetKeyName(629, "C3M (629).png")
        Me.ImageCollection1.Images.SetKeyName(630, "C3M (630).png")
        Me.ImageCollection1.Images.SetKeyName(631, "C3M (631).png")
        Me.ImageCollection1.Images.SetKeyName(632, "C3M (632).png")
        Me.ImageCollection1.Images.SetKeyName(633, "C3M (633).png")
        Me.ImageCollection1.Images.SetKeyName(634, "C3M (634).png")
        Me.ImageCollection1.Images.SetKeyName(635, "C3M (635).png")
        Me.ImageCollection1.Images.SetKeyName(636, "C3M (636).png")
        Me.ImageCollection1.Images.SetKeyName(637, "C3M (637).png")
        Me.ImageCollection1.Images.SetKeyName(638, "C3M (638).png")
        Me.ImageCollection1.Images.SetKeyName(639, "C3M (639).png")
        Me.ImageCollection1.Images.SetKeyName(640, "C3M (640).png")
        Me.ImageCollection1.Images.SetKeyName(641, "C3M (641).png")
        Me.ImageCollection1.Images.SetKeyName(642, "C3M (642).png")
        Me.ImageCollection1.Images.SetKeyName(643, "C3M (643).png")
        Me.ImageCollection1.Images.SetKeyName(644, "C3M (644).png")
        Me.ImageCollection1.Images.SetKeyName(645, "C3M (645).png")
        Me.ImageCollection1.Images.SetKeyName(646, "C3M (646).png")
        Me.ImageCollection1.Images.SetKeyName(647, "C3M (647).png")
        Me.ImageCollection1.Images.SetKeyName(648, "C3M (648).png")
        Me.ImageCollection1.Images.SetKeyName(649, "C3M (649).png")
        Me.ImageCollection1.Images.SetKeyName(650, "C3M (650).png")
        Me.ImageCollection1.Images.SetKeyName(651, "C3M (651).png")
        Me.ImageCollection1.Images.SetKeyName(652, "C3M (652).png")
        Me.ImageCollection1.Images.SetKeyName(653, "C3M (653).png")
        Me.ImageCollection1.Images.SetKeyName(654, "C3M (654).png")
        Me.ImageCollection1.Images.SetKeyName(655, "C3M (655).png")
        Me.ImageCollection1.Images.SetKeyName(656, "C3M (656).png")
        Me.ImageCollection1.Images.SetKeyName(657, "C3M (657).png")
        Me.ImageCollection1.Images.SetKeyName(658, "C3M (658).png")
        Me.ImageCollection1.Images.SetKeyName(659, "C3M (659).png")
        Me.ImageCollection1.Images.SetKeyName(660, "C3M (660).png")
        Me.ImageCollection1.Images.SetKeyName(661, "C3M (661).png")
        Me.ImageCollection1.Images.SetKeyName(662, "C3M (662).png")
        Me.ImageCollection1.Images.SetKeyName(663, "C3M (663).png")
        Me.ImageCollection1.Images.SetKeyName(664, "C3M (664).png")
        Me.ImageCollection1.Images.SetKeyName(665, "C3M (665).png")
        Me.ImageCollection1.Images.SetKeyName(666, "C3M (666).png")
        Me.ImageCollection1.Images.SetKeyName(667, "C3M (667).png")
        Me.ImageCollection1.Images.SetKeyName(668, "C3M (668).png")
        Me.ImageCollection1.Images.SetKeyName(669, "C3M (669).png")
        Me.ImageCollection1.Images.SetKeyName(670, "C3M (670).png")
        Me.ImageCollection1.Images.SetKeyName(671, "C3M (671).png")
        Me.ImageCollection1.Images.SetKeyName(672, "C3M (672).png")
        Me.ImageCollection1.Images.SetKeyName(673, "C3M (673).png")
        Me.ImageCollection1.Images.SetKeyName(674, "C3M (674).png")
        Me.ImageCollection1.Images.SetKeyName(675, "C3M (675).png")
        Me.ImageCollection1.Images.SetKeyName(676, "C3M (676).png")
        Me.ImageCollection1.Images.SetKeyName(677, "C3M (677).png")
        Me.ImageCollection1.Images.SetKeyName(678, "C3M (678).png")
        Me.ImageCollection1.Images.SetKeyName(679, "C3M (679).png")
        Me.ImageCollection1.Images.SetKeyName(680, "C3M (680).png")
        Me.ImageCollection1.Images.SetKeyName(681, "C3M (681).png")
        Me.ImageCollection1.Images.SetKeyName(682, "C3M (682).png")
        Me.ImageCollection1.Images.SetKeyName(683, "C3M (683).png")
        Me.ImageCollection1.Images.SetKeyName(684, "C3M (684).png")
        Me.ImageCollection1.Images.SetKeyName(685, "C3M (685).png")
        Me.ImageCollection1.Images.SetKeyName(686, "C3M (686).png")
        Me.ImageCollection1.Images.SetKeyName(687, "C3M (687).png")
        Me.ImageCollection1.Images.SetKeyName(688, "C3M (688).png")
        Me.ImageCollection1.Images.SetKeyName(689, "C3M (689).png")
        Me.ImageCollection1.Images.SetKeyName(690, "C3M (690).png")
        Me.ImageCollection1.Images.SetKeyName(691, "C3M (691).png")
        Me.ImageCollection1.Images.SetKeyName(692, "C3M (692).png")
        Me.ImageCollection1.Images.SetKeyName(693, "C3M (693).png")
        Me.ImageCollection1.Images.SetKeyName(694, "C3M (694).png")
        Me.ImageCollection1.Images.SetKeyName(695, "C3M (695).png")
        Me.ImageCollection1.Images.SetKeyName(696, "C3M (696).png")
        Me.ImageCollection1.Images.SetKeyName(697, "C3M (697).png")
        Me.ImageCollection1.Images.SetKeyName(698, "C3M (698).png")
        Me.ImageCollection1.Images.SetKeyName(699, "C3M (699).png")
        Me.ImageCollection1.Images.SetKeyName(700, "C3M (700).png")
        Me.ImageCollection1.Images.SetKeyName(701, "C3M (701).png")
        Me.ImageCollection1.Images.SetKeyName(702, "C3M (702).png")
        Me.ImageCollection1.Images.SetKeyName(703, "C3M (703).png")
        Me.ImageCollection1.Images.SetKeyName(704, "C3M (704).png")
        Me.ImageCollection1.Images.SetKeyName(705, "C3M (705).png")
        Me.ImageCollection1.Images.SetKeyName(706, "C3M (706).png")
        Me.ImageCollection1.Images.SetKeyName(707, "C3M (707).png")
        Me.ImageCollection1.Images.SetKeyName(708, "C3M (708).png")
        Me.ImageCollection1.Images.SetKeyName(709, "C3M (709).png")
        Me.ImageCollection1.Images.SetKeyName(710, "C3M (710).png")
        Me.ImageCollection1.Images.SetKeyName(711, "C3M (711).png")
        Me.ImageCollection1.Images.SetKeyName(712, "C3M (712).png")
        Me.ImageCollection1.Images.SetKeyName(713, "C3M (713).png")
        Me.ImageCollection1.Images.SetKeyName(714, "C3M (714).png")
        Me.ImageCollection1.Images.SetKeyName(715, "C3M (715).png")
        Me.ImageCollection1.Images.SetKeyName(716, "C3M (716).png")
        Me.ImageCollection1.Images.SetKeyName(717, "C3M (717).png")
        Me.ImageCollection1.Images.SetKeyName(718, "C3M (718).png")
        Me.ImageCollection1.Images.SetKeyName(719, "C3M (719).png")
        Me.ImageCollection1.Images.SetKeyName(720, "C3M (720).png")
        Me.ImageCollection1.Images.SetKeyName(721, "C3M (721).png")
        Me.ImageCollection1.Images.SetKeyName(722, "C3M (722).png")
        Me.ImageCollection1.Images.SetKeyName(723, "C3M (723).png")
        Me.ImageCollection1.Images.SetKeyName(724, "C3M (724).png")
        Me.ImageCollection1.Images.SetKeyName(725, "C3M (725).png")
        Me.ImageCollection1.Images.SetKeyName(726, "C3M (726).png")
        Me.ImageCollection1.Images.SetKeyName(727, "C3M (727).png")
        Me.ImageCollection1.Images.SetKeyName(728, "C3M (728).png")
        Me.ImageCollection1.Images.SetKeyName(729, "C3M (729).png")
        Me.ImageCollection1.Images.SetKeyName(730, "C3M (730).png")
        Me.ImageCollection1.Images.SetKeyName(731, "C3M (731).png")
        Me.ImageCollection1.Images.SetKeyName(732, "C3M (732).png")
        Me.ImageCollection1.Images.SetKeyName(733, "C3M (734).png")
        Me.ImageCollection1.Images.SetKeyName(734, "C3M (735).png")
        Me.ImageCollection1.Images.SetKeyName(735, "C3M (736).png")
        Me.ImageCollection1.Images.SetKeyName(736, "C3M (737).png")
        Me.ImageCollection1.Images.SetKeyName(737, "C3M (738).png")
        Me.ImageCollection1.Images.SetKeyName(738, "C3M (739).png")
        Me.ImageCollection1.Images.SetKeyName(739, "C3M (740).png")
        Me.ImageCollection1.Images.SetKeyName(740, "C3M (741).png")
        Me.ImageCollection1.Images.SetKeyName(741, "C3M (742).png")
        Me.ImageCollection1.Images.SetKeyName(742, "C3M (743).png")
        Me.ImageCollection1.Images.SetKeyName(743, "C3M (744).png")
        Me.ImageCollection1.Images.SetKeyName(744, "C3M (745).png")
        Me.ImageCollection1.Images.SetKeyName(745, "C3M (746).png")
        Me.ImageCollection1.Images.SetKeyName(746, "C3M (747).png")
        Me.ImageCollection1.Images.SetKeyName(747, "C3M (748).png")
        Me.ImageCollection1.Images.SetKeyName(748, "C3M (749).png")
        Me.ImageCollection1.Images.SetKeyName(749, "C3M (750).png")
        Me.ImageCollection1.Images.SetKeyName(750, "C3M (751).png")
        Me.ImageCollection1.Images.SetKeyName(751, "C3M (752).png")
        Me.ImageCollection1.Images.SetKeyName(752, "C3M (753).png")
        Me.ImageCollection1.Images.SetKeyName(753, "C3M (754).png")
        Me.ImageCollection1.Images.SetKeyName(754, "C3M (755).png")
        Me.ImageCollection1.Images.SetKeyName(755, "C3M (756).png")
        Me.ImageCollection1.Images.SetKeyName(756, "C3M (757).png")
        Me.ImageCollection1.Images.SetKeyName(757, "C3M (758).png")
        Me.ImageCollection1.Images.SetKeyName(758, "C3M (759).png")
        Me.ImageCollection1.Images.SetKeyName(759, "C3M (760).png")
        Me.ImageCollection1.Images.SetKeyName(760, "C3M (761).png")
        Me.ImageCollection1.Images.SetKeyName(761, "C3M (762).png")
        Me.ImageCollection1.Images.SetKeyName(762, "C3M (763).png")
        Me.ImageCollection1.Images.SetKeyName(763, "C3M (764).png")
        Me.ImageCollection1.Images.SetKeyName(764, "C3M (765).png")
        Me.ImageCollection1.Images.SetKeyName(765, "C3M (766).png")
        Me.ImageCollection1.Images.SetKeyName(766, "C3M (767).png")
        Me.ImageCollection1.Images.SetKeyName(767, "C3M (768).png")
        Me.ImageCollection1.Images.SetKeyName(768, "C3M (769).png")
        Me.ImageCollection1.Images.SetKeyName(769, "C3M (770).png")
        Me.ImageCollection1.Images.SetKeyName(770, "C3M (771).png")
        Me.ImageCollection1.Images.SetKeyName(771, "C3M (772).png")
        Me.ImageCollection1.Images.SetKeyName(772, "C3M (773).png")
        Me.ImageCollection1.Images.SetKeyName(773, "C3M (774).png")
        Me.ImageCollection1.Images.SetKeyName(774, "C3M (775).png")
        Me.ImageCollection1.Images.SetKeyName(775, "C3M (776).png")
        Me.ImageCollection1.Images.SetKeyName(776, "C3M (777).png")
        Me.ImageCollection1.Images.SetKeyName(777, "C3M (778).png")
        Me.ImageCollection1.Images.SetKeyName(778, "C3M (779).png")
        Me.ImageCollection1.Images.SetKeyName(779, "C3M (780).png")
        Me.ImageCollection1.Images.SetKeyName(780, "C3M (781).png")
        Me.ImageCollection1.Images.SetKeyName(781, "C3M (782).png")
        Me.ImageCollection1.Images.SetKeyName(782, "C3M (783).png")
        Me.ImageCollection1.Images.SetKeyName(783, "C3M (784).png")
        Me.ImageCollection1.Images.SetKeyName(784, "C3M (785).png")
        Me.ImageCollection1.Images.SetKeyName(785, "C3M (786).png")
        Me.ImageCollection1.Images.SetKeyName(786, "C3M (787).png")
        Me.ImageCollection1.Images.SetKeyName(787, "C3M (788).png")
        Me.ImageCollection1.Images.SetKeyName(788, "C3M (789).png")
        Me.ImageCollection1.Images.SetKeyName(789, "C3M (790).png")
        Me.ImageCollection1.Images.SetKeyName(790, "C3M (791).png")
        Me.ImageCollection1.Images.SetKeyName(791, "C3M (792).png")
        Me.ImageCollection1.Images.SetKeyName(792, "C3M (793).png")
        Me.ImageCollection1.Images.SetKeyName(793, "C3M (794).png")
        Me.ImageCollection1.Images.SetKeyName(794, "C3M (795).png")
        Me.ImageCollection1.Images.SetKeyName(795, "C3M (796).png")
        Me.ImageCollection1.Images.SetKeyName(796, "C3M (797).png")
        Me.ImageCollection1.Images.SetKeyName(797, "C3M (798).png")
        Me.ImageCollection1.Images.SetKeyName(798, "C3M (799).png")
        Me.ImageCollection1.Images.SetKeyName(799, "C3M (800).png")
        Me.ImageCollection1.Images.SetKeyName(800, "C3M (801).png")
        Me.ImageCollection1.Images.SetKeyName(801, "C3M (802).png")
        Me.ImageCollection1.Images.SetKeyName(802, "C3M (803).png")
        Me.ImageCollection1.Images.SetKeyName(803, "C3M (804).png")
        Me.ImageCollection1.Images.SetKeyName(804, "C3M (805).png")
        Me.ImageCollection1.Images.SetKeyName(805, "C3M (806).png")
        Me.ImageCollection1.Images.SetKeyName(806, "C3M (807).png")
        Me.ImageCollection1.Images.SetKeyName(807, "C3M (808).png")
        Me.ImageCollection1.Images.SetKeyName(808, "C3M (809).png")
        Me.ImageCollection1.Images.SetKeyName(809, "C3M (810).png")
        Me.ImageCollection1.Images.SetKeyName(810, "C3M (811).png")
        Me.ImageCollection1.Images.SetKeyName(811, "C3M (812).png")
        Me.ImageCollection1.Images.SetKeyName(812, "C3M (813).png")
        Me.ImageCollection1.Images.SetKeyName(813, "C3M (814).png")
        Me.ImageCollection1.Images.SetKeyName(814, "C3M (815).png")
        Me.ImageCollection1.Images.SetKeyName(815, "C3M (816).png")
        Me.ImageCollection1.Images.SetKeyName(816, "C3M (817).png")
        Me.ImageCollection1.Images.SetKeyName(817, "C3M (818).png")
        Me.ImageCollection1.Images.SetKeyName(818, "C3M (819).png")
        Me.ImageCollection1.Images.SetKeyName(819, "C3M (820).png")
        Me.ImageCollection1.Images.SetKeyName(820, "C3M (821).png")
        Me.ImageCollection1.Images.SetKeyName(821, "C3M (822).png")
        Me.ImageCollection1.Images.SetKeyName(822, "C3M (823).png")
        Me.ImageCollection1.Images.SetKeyName(823, "C3M (824).png")
        Me.ImageCollection1.Images.SetKeyName(824, "C3M (825).png")
        Me.ImageCollection1.Images.SetKeyName(825, "C3M (826).png")
        Me.ImageCollection1.Images.SetKeyName(826, "C3M (827).png")
        Me.ImageCollection1.Images.SetKeyName(827, "C3M (828).png")
        Me.ImageCollection1.Images.SetKeyName(828, "C3M (829).png")
        Me.ImageCollection1.Images.SetKeyName(829, "C3M (830).png")
        Me.ImageCollection1.Images.SetKeyName(830, "C3M (831).png")
        Me.ImageCollection1.Images.SetKeyName(831, "C3M (832).png")
        Me.ImageCollection1.Images.SetKeyName(832, "C3M (833).png")
        Me.ImageCollection1.Images.SetKeyName(833, "C3M (834).png")
        Me.ImageCollection1.Images.SetKeyName(834, "C3M (835).png")
        Me.ImageCollection1.Images.SetKeyName(835, "C3M (836).png")
        Me.ImageCollection1.Images.SetKeyName(836, "C3M (837).png")
        Me.ImageCollection1.Images.SetKeyName(837, "C3M (838).png")
        Me.ImageCollection1.Images.SetKeyName(838, "C3M (839).png")
        Me.ImageCollection1.Images.SetKeyName(839, "C3M (840).png")
        Me.ImageCollection1.Images.SetKeyName(840, "C3M (841).png")
        Me.ImageCollection1.Images.SetKeyName(841, "C3M (842).png")
        Me.ImageCollection1.Images.SetKeyName(842, "C3M (843).png")
        Me.ImageCollection1.Images.SetKeyName(843, "C3M (844).png")
        Me.ImageCollection1.Images.SetKeyName(844, "C3M (845).png")
        Me.ImageCollection1.Images.SetKeyName(845, "C3M (846).png")
        Me.ImageCollection1.Images.SetKeyName(846, "C3M (847).png")
        Me.ImageCollection1.Images.SetKeyName(847, "C3M (848).png")
        Me.ImageCollection1.Images.SetKeyName(848, "C3M (849).png")
        Me.ImageCollection1.Images.SetKeyName(849, "C3M (850).png")
        Me.ImageCollection1.Images.SetKeyName(850, "C3M (851).png")
        Me.ImageCollection1.Images.SetKeyName(851, "C3M (852).png")
        Me.ImageCollection1.Images.SetKeyName(852, "C3M (853).png")
        Me.ImageCollection1.Images.SetKeyName(853, "C3M (854).png")
        Me.ImageCollection1.Images.SetKeyName(854, "C3M (855).png")
        Me.ImageCollection1.Images.SetKeyName(855, "C3M (856).png")
        Me.ImageCollection1.Images.SetKeyName(856, "C3M (857).png")
        Me.ImageCollection1.Images.SetKeyName(857, "C3M (858).png")
        Me.ImageCollection1.Images.SetKeyName(858, "C3M (859).png")
        Me.ImageCollection1.Images.SetKeyName(859, "C3M (860).png")
        Me.ImageCollection1.Images.SetKeyName(860, "C3M (861).png")
        Me.ImageCollection1.Images.SetKeyName(861, "C3M (862).png")
        Me.ImageCollection1.Images.SetKeyName(862, "C3M (863).png")
        Me.ImageCollection1.Images.SetKeyName(863, "C3M (864).png")
        Me.ImageCollection1.Images.SetKeyName(864, "C3M (865).png")
        Me.ImageCollection1.Images.SetKeyName(865, "C3M (866).png")
        Me.ImageCollection1.Images.SetKeyName(866, "C3M (867).png")
        Me.ImageCollection1.Images.SetKeyName(867, "C3M (868).png")
        Me.ImageCollection1.Images.SetKeyName(868, "C3M (869).png")
        Me.ImageCollection1.Images.SetKeyName(869, "C3M (870).png")
        Me.ImageCollection1.Images.SetKeyName(870, "C3M (871).png")
        Me.ImageCollection1.Images.SetKeyName(871, "C3M (872).png")
        Me.ImageCollection1.Images.SetKeyName(872, "C3M (873).png")
        Me.ImageCollection1.Images.SetKeyName(873, "C3M (874).png")
        Me.ImageCollection1.Images.SetKeyName(874, "C3M (875).png")
        Me.ImageCollection1.Images.SetKeyName(875, "C3M (876).png")
        Me.ImageCollection1.Images.SetKeyName(876, "C3M (877).png")
        Me.ImageCollection1.Images.SetKeyName(877, "C3M (878).png")
        Me.ImageCollection1.Images.SetKeyName(878, "C3M (879).png")
        Me.ImageCollection1.Images.SetKeyName(879, "C3M (880).png")
        Me.ImageCollection1.Images.SetKeyName(880, "C3M (881).png")
        Me.ImageCollection1.Images.SetKeyName(881, "C3M (882).png")
        Me.ImageCollection1.Images.SetKeyName(882, "C3M (883).png")
        Me.ImageCollection1.Images.SetKeyName(883, "C3M (884).png")
        Me.ImageCollection1.Images.SetKeyName(884, "C3M (885).png")
        Me.ImageCollection1.Images.SetKeyName(885, "C3M (886).png")
        Me.ImageCollection1.Images.SetKeyName(886, "C3M (887).png")
        Me.ImageCollection1.Images.SetKeyName(887, "C3M (888).png")
        Me.ImageCollection1.Images.SetKeyName(888, "C3M (889).png")
        Me.ImageCollection1.Images.SetKeyName(889, "C3M (890).png")
        Me.ImageCollection1.Images.SetKeyName(890, "C3M (891).png")
        Me.ImageCollection1.Images.SetKeyName(891, "C3M (892).png")
        Me.ImageCollection1.Images.SetKeyName(892, "C3M (893).png")
        Me.ImageCollection1.Images.SetKeyName(893, "C3M (894).png")
        Me.ImageCollection1.Images.SetKeyName(894, "C3M (895).png")
        Me.ImageCollection1.Images.SetKeyName(895, "C3M (896).png")
        Me.ImageCollection1.Images.SetKeyName(896, "C3M (897).png")
        Me.ImageCollection1.Images.SetKeyName(897, "C3M (898).png")
        Me.ImageCollection1.Images.SetKeyName(898, "C3M (899).png")
        Me.ImageCollection1.Images.SetKeyName(899, "C3M (900).png")
        Me.ImageCollection1.Images.SetKeyName(900, "C3M (901).png")
        Me.ImageCollection1.Images.SetKeyName(901, "C3M (902).png")
        Me.ImageCollection1.Images.SetKeyName(902, "C3M (903).png")
        Me.ImageCollection1.Images.SetKeyName(903, "C3M (904).png")
        Me.ImageCollection1.Images.SetKeyName(904, "C3M (905).png")
        Me.ImageCollection1.Images.SetKeyName(905, "C3M (906).png")
        Me.ImageCollection1.Images.SetKeyName(906, "C3M (907).png")
        Me.ImageCollection1.Images.SetKeyName(907, "C3M (908).png")
        Me.ImageCollection1.Images.SetKeyName(908, "C3M (909).png")
        '
        'BarButtonItem3
        '
        Me.BarButtonItem3.Caption = "BarButtonItem3"
        Me.BarButtonItem3.Id = 5
        Me.BarButtonItem3.ImageIndex = 38
        Me.BarButtonItem3.Name = "BarButtonItem3"
        '
        'BarButtonItem4
        '
        Me.BarButtonItem4.Caption = "BarButtonItem4"
        Me.BarButtonItem4.Id = 6
        Me.BarButtonItem4.ImageIndex = 78
        Me.BarButtonItem4.Name = "BarButtonItem4"
        '
        'BarStaticItem1
        '
        Me.BarStaticItem1.Alignment = DevExpress.XtraBars.BarItemLinkAlignment.Right
        Me.BarStaticItem1.Caption = "Version 1.0.0"
        Me.BarStaticItem1.Id = 7
        Me.BarStaticItem1.Name = "BarStaticItem1"
        Me.BarStaticItem1.TextAlignment = System.Drawing.StringAlignment.Near
        '
        'BarButtonItem5
        '
        Me.BarButtonItem5.Caption = "Wallpaper"
        Me.BarButtonItem5.Id = 10
        Me.BarButtonItem5.ImageIndex = 298
        Me.BarButtonItem5.LargeImageIndex = 298
        Me.BarButtonItem5.Name = "BarButtonItem5"
        '
        'BarButtonItem6
        '
        Me.BarButtonItem6.Caption = "Konfigurasi Server"
        Me.BarButtonItem6.Id = 11
        Me.BarButtonItem6.ImageIndex = 150
        Me.BarButtonItem6.LargeImageIndex = 150
        Me.BarButtonItem6.Name = "BarButtonItem6"
        '
        'BarButtonItem7
        '
        Me.BarButtonItem7.Caption = "Hak Akses"
        Me.BarButtonItem7.Id = 12
        Me.BarButtonItem7.ImageIndex = 92
        Me.BarButtonItem7.LargeImageIndex = 92
        Me.BarButtonItem7.Name = "BarButtonItem7"
        '
        'BarButtonItem8
        '
        Me.BarButtonItem8.Caption = "Pengguna"
        Me.BarButtonItem8.Id = 13
        Me.BarButtonItem8.ImageIndex = 186
        Me.BarButtonItem8.LargeImageIndex = 186
        Me.BarButtonItem8.Name = "BarButtonItem8"
        '
        'BarButtonItem9
        '
        Me.BarButtonItem9.Caption = "MENU"
        Me.BarButtonItem9.Id = 14
        Me.BarButtonItem9.ImageIndex = 892
        Me.BarButtonItem9.LargeImageIndex = 892
        Me.BarButtonItem9.Name = "BarButtonItem9"
        '
        'BarButtonItem10
        '
        Me.BarButtonItem10.Caption = "PELANGGAN"
        Me.BarButtonItem10.Id = 15
        Me.BarButtonItem10.ImageIndex = 331
        Me.BarButtonItem10.LargeImageIndex = 331
        Me.BarButtonItem10.Name = "BarButtonItem10"
        '
        'BarButtonItem11
        '
        Me.BarButtonItem11.Caption = "PEMESANAN"
        Me.BarButtonItem11.Id = 16
        Me.BarButtonItem11.ImageIndex = 880
        Me.BarButtonItem11.LargeImageIndex = 880
        Me.BarButtonItem11.Name = "BarButtonItem11"
        '
        'BarButtonItem12
        '
        Me.BarButtonItem12.Caption = "PEMBAYARAN"
        Me.BarButtonItem12.Id = 17
        Me.BarButtonItem12.ImageIndex = 781
        Me.BarButtonItem12.LargeImageIndex = 781
        Me.BarButtonItem12.Name = "BarButtonItem12"
        '
        'RibbonGalleryBarItem1
        '
        Me.RibbonGalleryBarItem1.Caption = "RibbonGalleryBarItem1"
        Me.RibbonGalleryBarItem1.Id = 18
        Me.RibbonGalleryBarItem1.Name = "RibbonGalleryBarItem1"
        '
        'RibbonPage1
        '
        Me.RibbonPage1.Groups.AddRange(New DevExpress.XtraBars.Ribbon.RibbonPageGroup() {Me.RibbonPageGroup1, Me.RibbonPageGroup2, Me.RibbonPageGroup3})
        Me.RibbonPage1.Name = "RibbonPage1"
        Me.RibbonPage1.Text = "MENU"
        '
        'RibbonPageGroup1
        '
        Me.RibbonPageGroup1.ItemLinks.Add(Me.BarButtonItem9)
        Me.RibbonPageGroup1.ItemLinks.Add(Me.BarButtonItem10)
        Me.RibbonPageGroup1.Name = "RibbonPageGroup1"
        Me.RibbonPageGroup1.Text = "Referensi"
        '
        'RibbonPageGroup2
        '
        Me.RibbonPageGroup2.ItemLinks.Add(Me.BarButtonItem11)
        Me.RibbonPageGroup2.ItemLinks.Add(Me.BarButtonItem12)
        Me.RibbonPageGroup2.Name = "RibbonPageGroup2"
        Me.RibbonPageGroup2.Text = "Transaksi"
        '
        'RibbonPageGroup3
        '
        Me.RibbonPageGroup3.ItemLinks.Add(Me.BarButtonItem13, True)
        Me.RibbonPageGroup3.Name = "RibbonPageGroup3"
        Me.RibbonPageGroup3.Text = "Laporan"
        '
        'RibbonPage2
        '
        Me.RibbonPage2.Groups.AddRange(New DevExpress.XtraBars.Ribbon.RibbonPageGroup() {Me.RibbonPageGroup4})
        Me.RibbonPage2.Name = "RibbonPage2"
        Me.RibbonPage2.Text = "PENGATURAN"
        '
        'RibbonPageGroup4
        '
        Me.RibbonPageGroup4.ItemLinks.Add(Me.RibbonGalleryBarItem1)
        Me.RibbonPageGroup4.ItemLinks.Add(Me.BarButtonItem5)
        Me.RibbonPageGroup4.ItemLinks.Add(Me.BarButtonItem6)
        Me.RibbonPageGroup4.ItemLinks.Add(Me.BarButtonItem7)
        Me.RibbonPageGroup4.ItemLinks.Add(Me.BarButtonItem8)
        Me.RibbonPageGroup4.Name = "RibbonPageGroup4"
        Me.RibbonPageGroup4.Text = "Umum"
        '
        'RibbonStatusBar
        '
        Me.RibbonStatusBar.ItemLinks.Add(Me.BarButtonItem3)
        Me.RibbonStatusBar.ItemLinks.Add(Me.BarButtonItem4)
        Me.RibbonStatusBar.ItemLinks.Add(Me.BarStaticItem1)
        Me.RibbonStatusBar.Location = New System.Drawing.Point(0, 568)
        Me.RibbonStatusBar.Name = "RibbonStatusBar"
        Me.RibbonStatusBar.Ribbon = Me.RibbonControl
        Me.RibbonStatusBar.Size = New System.Drawing.Size(790, 31)
        '
        'DocumentManager1
        '
        Me.DocumentManager1.MdiParent = Me
        Me.DocumentManager1.MenuManager = Me.RibbonControl
        Me.DocumentManager1.View = Me.TabbedView1
        Me.DocumentManager1.ViewCollection.AddRange(New DevExpress.XtraBars.Docking2010.Views.BaseView() {Me.TabbedView1})
        '
        'TabbedView1
        '
        Me.TabbedView1.RootContainer.Element = Nothing
        '
        'Timer1
        '
        '
        'BarButtonItem13
        '
        Me.BarButtonItem13.Caption = "LAPORAN TRANSAKSI"
        Me.BarButtonItem13.Id = 20
        Me.BarButtonItem13.ImageIndex = 469
        Me.BarButtonItem13.LargeImageIndex = 469
        Me.BarButtonItem13.Name = "BarButtonItem13"
        '
        'frmSetupMenuUtama
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 13.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(790, 599)
        Me.Controls.Add(Me.RibbonStatusBar)
        Me.Controls.Add(Me.RibbonControl)
        Me.IsMdiContainer = True
        Me.Name = "frmSetupMenuUtama"
        Me.Ribbon = Me.RibbonControl
        Me.StatusBar = Me.RibbonStatusBar
        Me.Text = "APLIKASI KASIR RESTORAN"
        Me.WindowState = System.Windows.Forms.FormWindowState.Maximized
        CType(Me.RibbonControl, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ApplicationMenu1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ImageCollection1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.DocumentManager1, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.TabbedView1, System.ComponentModel.ISupportInitialize).EndInit()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub

    Friend WithEvents RibbonControl As DevExpress.XtraBars.Ribbon.RibbonControl
    Friend WithEvents RibbonPage1 As DevExpress.XtraBars.Ribbon.RibbonPage
    Friend WithEvents RibbonPageGroup1 As DevExpress.XtraBars.Ribbon.RibbonPageGroup
    Friend WithEvents RibbonStatusBar As DevExpress.XtraBars.Ribbon.RibbonStatusBar
    Friend WithEvents RibbonPageGroup2 As DevExpress.XtraBars.Ribbon.RibbonPageGroup
    Friend WithEvents RibbonPageGroup3 As DevExpress.XtraBars.Ribbon.RibbonPageGroup
    Friend WithEvents RibbonPage2 As DevExpress.XtraBars.Ribbon.RibbonPage
    Friend WithEvents ApplicationMenu1 As DevExpress.XtraBars.Ribbon.ApplicationMenu
    Friend WithEvents BarButtonItem1 As DevExpress.XtraBars.BarButtonItem
    Friend WithEvents BarButtonItem2 As DevExpress.XtraBars.BarButtonItem
    Friend WithEvents ImageCollection1 As DevExpress.Utils.ImageCollection
    Friend WithEvents BarButtonItem3 As DevExpress.XtraBars.BarButtonItem
    Friend WithEvents BarButtonItem4 As DevExpress.XtraBars.BarButtonItem
    Friend WithEvents BarStaticItem1 As DevExpress.XtraBars.BarStaticItem
    Friend WithEvents BarButtonItem5 As DevExpress.XtraBars.BarButtonItem
    Friend WithEvents BarButtonItem6 As DevExpress.XtraBars.BarButtonItem
    Friend WithEvents BarButtonItem7 As DevExpress.XtraBars.BarButtonItem
    Friend WithEvents BarButtonItem8 As DevExpress.XtraBars.BarButtonItem
    Friend WithEvents RibbonPageGroup4 As DevExpress.XtraBars.Ribbon.RibbonPageGroup
    Friend WithEvents DocumentManager1 As DevExpress.XtraBars.Docking2010.DocumentManager
    Friend WithEvents TabbedView1 As DevExpress.XtraBars.Docking2010.Views.Tabbed.TabbedView
    Friend WithEvents Timer1 As System.Windows.Forms.Timer
    Friend WithEvents BarButtonItem9 As DevExpress.XtraBars.BarButtonItem
    Friend WithEvents BarButtonItem10 As DevExpress.XtraBars.BarButtonItem
    Friend WithEvents BarButtonItem11 As DevExpress.XtraBars.BarButtonItem
    Friend WithEvents BarButtonItem12 As DevExpress.XtraBars.BarButtonItem
    Friend WithEvents RibbonGalleryBarItem1 As DevExpress.XtraBars.RibbonGalleryBarItem
    Friend WithEvents BarButtonItem13 As DevExpress.XtraBars.BarButtonItem


End Class
